Update init script/unit file
Update init script to conform to the LSB 5.0 standard.
Also remove dependency on /proc/i8k to support
systems without CONFIG_I8K.

diff --git a/etc/i8kmon b/etc/i8kmon
--- a/etc/i8kmon
+++ b/etc/i8kmon
@@ -22,42 +22,58 @@
 #		Massimo Dal Zotto <dz@debian.org> and
 #		Bradley Smith <bradsmith@debian.org>
 #		Updated by Vitor Augusto <vitorafsr@gmail.com>.
+#		Updated by Armin Wolf <W_Armin@gmx.de>.
 
-PATH=/sbin:/bin:/usr/sbin:/usr/bin
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
+NAME=i8kmon
+DAEMON=/usr/bin/i8kmon
+DESC="DELL notebook fan control"
+PIDFILE=/var/run/$NAME.pid
+HWMON_DEV="dell_smm"
 
 . /lib/lsb/init-functions
 
-NAME=i8kmon
-DAEMON=/usr/bin/i8kmon
-PROC_I8K=/proc/i8k
-DESC="Fan control for Dell laptops"
-PIDFILE=/var/run/$NAME.pid
-
-test -x $DAEMON || (log_failure_msg "Could not find $DAEMON."; exit 5)
-
 case "$1" in
 	start)
+		test -f $DAEMON || exit 5
+
 		log_success_msg "Starting $DESC" "$NAME"
-		if [ ! -f "$PROC_I8K" ]; then
-			log_failure_msg "Could not find $PROC_I8K."
-			exit 1
-		fi
-		start-stop-daemon --start --quiet --pidfile $PIDFILE \
-			--background --make-pidfile --startas $DAEMON
+		for ENTRY in /sys/class/hwmon/hwmon*/name
+		do
+			if [ $(cat $ENTRY) = $HWMON_DEV ]
+			then
+				start-stop-daemon --start --quiet --oknodo \
+					--pidfile $PIDFILE --background --make-pidfile \
+					--startas $DAEMON --chuid 0
+
+				[ $? -eq 0 ] && exit 0
+
+				exit 1
+			fi
+		done
+
+		log_failure_msg "Could not find hwmon device ($HWMON_DEV)"
+		exit 1
 		;;
 	stop)
 		log_success_msg "Stopping $DESC" "$NAME"
-		start-stop-daemon --oknodo --stop --quiet --pidfile $PIDFILE
-		rm -f $PIDFILE
+		start-stop-daemon --oknodo --stop --quiet --pidfile $PIDFILE \
+			--remove-pidfile
+
+		[ $? -eq 0 ] && exit 0
+
+		exit 1
 		;;
 	status)
 		status_of_proc -p $PIDFILE $DAEMON $NAME
 		;;
-	restart|reload|force-reload)
-		$0 stop && sleep 2 && $0 start
+	restart|force-reload)
+		$0 stop
+		sleep 2
+		$0 start
 		;;
 	*)
-		echo "Usage: $0 {start|stop|status|restart|reload|force-reload}" >&2
-	    exit 2
+		echo "Usage: $0 {start|stop|status|restart|force-reload}" >&2
+		exit 2
 		;;
 esac
